In [ ]:
!git clone https://github.com/suhas2071/datafiles.git

Cloning into 'datafiles'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 120 (delta 31), reused 54 (delta 12), pack-reused 3 (from 1)
Receiving objects: 100% (120/120), 23.97 MiB | 12.05 MiB/s, done.
Resolving deltas: 100% (31/31), done.


In [ ]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('/content/datafiles/diabetes.csv')
dataset.head()
#Outcome -Target
#Diabetic prediction model for Hospital

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
dataset.shape

(768, 9)

In [ ]:
dataset[['Age','Outcome']].corr()

Age   Outcome
Age      1.000000  0.238356
Outcome  0.238356  1.000000

In [ ]:
dataset[['Glucose','Outcome']].corr()

Glucose   Outcome
Glucose  1.000000  0.465754
Outcome  0.465754  1.000000

In [ ]:
dataset[['BMI','Outcome']].corr()

BMI   Outcome
BMI      1.000000  0.292695
Outcome  0.292695  1.000000

In [ ]:
dataset[['BloodPressure','Outcome']].corr()

BloodPressure   Outcome
BloodPressure       1.000000  0.058972
Outcome             0.058972  1.000000

In [ ]:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X = dataset.drop('Outcome', axis=1)
X


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             74             23      112  26.2   
766            1      126              0              0        0  30.1   
767            1      128             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
y = dataset['Outcome']
y


0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43,stratify=y)

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43)


In [ ]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
305            2      120             76             37      105  39.7   
49             7      105              0              0        0   0.0   
676            9      156             86              0        0  24.8   
333           12      106             80              0        0  23.6   
336            0      117              0              0        0  33.8   
..           ...      ...            ...            ...      ...   ...   
29             5      117             92              0        0  34.1   
322            0      124             70             20        0  27.4   
526            1       97             64             19       82  18.2   
295            6      151             62             31      120  35.5   
75             1        0             48             20        0  24.7   

     DiabetesPedigreeFunction  Age  
305                     0.215   29  
49                      0.305   24  
676                     0.230   53  
333                     0.137   44  
336                     0.932   44  
..                        ...  ...  
29                      0.337   38  
322                     0.254   36  
526                     0.299   21  
295                     0.692   28  
75                      0.140   22  

[614 rows x 8 columns]

In [ ]:
y_train

305    0
49     0
676    1
333    0
336    0
      ..
29     0
322    1
526    0
295    0
75     0
Name: Outcome, Length: 614, dtype: int64

In [ ]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion='entropy')

classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
#from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
#from sklearn.tree import DecisionTreeClassifier

#classifier = DecisionTreeClassifier(criterion='entropy')

classifier = RandomForestClassifier(n_estimators=350,criterion='entropy',max_depth=10)
classifier.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=350)

In [ ]:
X_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
303            5      115             98              0        0  52.9   
755            1      128             88             39      110  36.5   
115            4      146             92              0        0  31.2   
564            0       91             80              0        0  32.4   
583            8      100             76              0        0  38.7   
..           ...      ...            ...            ...      ...   ...   
405            2      123             48             32      165  42.1   
302            5       77             82             41       42  35.8   
595            0      188             82             14      185  32.0   
560            6      125             76              0        0  33.8   
648           11      136             84             35      130  28.3   

     DiabetesPedigreeFunction  Age  
303                     0.209   28  
755                     1.057   37  
115                     0.539   61  
564                     0.601   27  
583                     0.190   42  
..                        ...  ...  
405                     0.520   26  
302                     0.156   35  
595                     0.682   22  
560                     0.121   54  
648                     0.260   42  

[154 rows x 8 columns]

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1])

In [ ]:
y_test

303    1
755    1
115    1
564    0
583    0
      ..
405    0
302    0
595    1
560    1
648    1
Name: Outcome, Length: 154, dtype: int64

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [ ]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics

print(" model accuracy:", metrics.accuracy_score(y_test, y_pred))

 model accuracy: 0.7987012987012987


In [ ]:
#Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age
sample=[[1,189,60,23,846,30.1,0.398,59]]

preds= classifier.predict(sample)
print("Predictions:", preds)

Predictions: [1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
import pickle
with open("model.pkl",'wb') as model_pkl:
    pickle.dump(classifier,model_pkl)

In [ ]:
import pickle
with open('/content/model.pkl','rb') as model_file:
    model_suhas=pickle.load(model_file)

In [ ]:
# making prediction for out of sample data
sample = [[6,148,72,35,0,33.6,0.627,50]]
preds = model_suhas.predict(sample)
print(preds)

[1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [ ]:
classifier.score(X_test, y_test)

0.7987012987012987

In [ ]:
classifier.score(X_train, y_train)

0.998371335504886

In [ ]:
Its means overfitting
You should:
1.Always split the data and try to achieve high accuracy on the test set rather than the training set.
2.If your training data accuracy is quite higher than the test data this means your modell is overfitting.

Your model is overfitting to your training data.
You need to try to tune the hyperpharameters so it will get a good accuracy when the you split the data.
Otherwise model is not that useful.

In [ ]:


sample=[[1,189,60,23,846,30.1,0.398,59]]

preds= classifier.predict(sample)
print("Predictions:", preds)

Predictions: [1]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.metrics import f1_score

#y_pred_class = y_pred_pos > threshold
f1_score(y_test, y_pred)

0.6666666666666666

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[92,  8],
       [23, 31]])

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.5740740740740741

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.7948717948717948

In [ ]:
treshhold =

1
0
0.6
44% - 0
56% - 0
72% - 1
32% - 0



In [ ]:

sample=[[1,85,66,29,0,26.6,0.351,31]]

preds= classifier.predict(sample)
print("Predictions:", preds)

Predictions: [0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
