In [1]:
import numpy as np

In [2]:
np1 = np.array([0,1,2,3,4,5])
print(np1)

[0 1 2 3 4 5]


In [3]:
np1.shape

(6,)

In [ ]:
#Range
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Step
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


In [ ]:
#Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#multidimensional zeros
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
#Full
np6 = np.full((10), 6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [11]:
#Multidimensional full
np7 = np.full((2,6), 5)
print(np7)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [12]:
#convert python list to numpy
mylist = [1,2,3,4,5]
np8 = np.array(mylist)
print(np8)

[1 2 3 4 5]


In [13]:
print(np8[1])

2


In [ ]:
#slicing
np9 = np.arange(10)
print(np9)
print(np9[-3:-1])
print(np9[::2])

[0 1 2 3 4 5 6 7 8 9]
[7 8]
[0 2 4 6 8]


In [22]:
#slicing 2D
np10 = np.array([
    [1,2,3,4], 
    [5,6,7,8]
    ])
print(np10)
print(np10[1,2])
print(np10[0:1,1:3])
print(np10[0:2, 1:3])
print(np10[:, 1:3])

[[1 2 3 4]
 [5 6 7 8]]
7
[[2 3]]
[[2 3]
 [6 7]]
[[2 3]
 [6 7]]
