In [1]:
import numpy as np

In [2]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#square root
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [5]:
#absolute value
np2 = np.array([-1,-2,-3,0,1])
print(np2)
print(np.absolute(np2))

[-1 -2 -3  0  1]
[1 2 3 0 1]


In [7]:
#exponentials
print(np1)
print(np.exp(np1))

[0 1 2 3 4 5 6 7 8 9]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [9]:
#min/max
print(np1)
print(np.max(np1))
print(np.min(np1))

[0 1 2 3 4 5 6 7 8 9]
9
0


In [10]:
#sign
print(np2)
print(np.sign(np2))

[-1 -2 -3  0  1]
[-1 -1 -1  0  1]


In [11]:
#sin, cos, log
print(np1)
print(np.sin(np1))
print(np.log(np1))

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\a812616\AppData\Local\Temp\ipykernel_25016\3045230111.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))


In [12]:
#argument of max value
print(np2)
print(np.argmax(np2))

[-1 -2 -3  0  1]
4


Copy vs View

In [15]:
np1 = np.array([1,2,3,4,5])
np2 = np1.view()
print(f"Original {np1}")
print(f"View {np2}")

Original [1 2 3 4 5]
View [1 2 3 4 5]


In [16]:
np1[0] = 25
print(f"Original {np1}")
print(f"View {np2}")

Original [25  2  3  4  5]
View [25  2  3  4  5]


In [17]:
np2[0] = 35
print(f"Original {np1}")
print(f"View {np2}")

Original [35  2  3  4  5]
View [35  2  3  4  5]


In [18]:
np1 = np.array([10,11,12,13,14])
np2 = np1.copy()
print(f"Original {np1}")
print(f"Copy {np2}")

Original [10 11 12 13 14]
Copy [10 11 12 13 14]


In [19]:
np1[0] = 25
print(f"Original {np1}")
print(f"Copy {np2}")

Original [25 11 12 13 14]
Copy [10 11 12 13 14]


In [20]:
np2[0] = 35
print(f"Original {np1}")
print(f"Copy {np2}")

Original [25 11 12 13 14]
Copy [35 11 12 13 14]
