In [2]:
import numpy as np

In [3]:
#1D array
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np1.shape

(12,)

In [ ]:
#2D array (rows, columns)
np2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
np2.shape

(2, 6)

In [8]:
#reshape
np3 = np1.reshape(3,4)
print(np1)
print(np3)
print(np3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [9]:
#reshape 3D
np4 = np1.reshape(2,3,2)
print(np4)
np4.shape

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


(2, 3, 2)

In [12]:
#Flatten to 1D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


Numpy Iteration

In [3]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for val in np1:
    print(val)

1
2
3
4
5
6
7
8
9
10


In [4]:
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
for val in np2:#print rows
    print(val)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [5]:
np3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
print(np3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
for x in np3:
    #print(x)
    for y in x:
        #print(y)
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#Use np.nditer()
for val in np.nditer(np3):
    print(val)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
for val in np.nditer(np2):
    print(val)

1
2
3
4
5
6
7
8
9
10


In [11]:
for val in np.nditer(np1):
    print(val)

1
2
3
4
5
6
7
8
9
10


##Sorting numpy arrays

In [ ]:
#np.sort() ascending order
np1 = np.array([6,7,8,9,2,4,1,3])
print(np.sort(np1))

[1 2 3 4 6 7 8 9]


In [13]:
np2 = np.array(['John', "Tina", "Aron", "Zed"])
print(np.sort(np2))

['Aron' 'John' 'Tina' 'Zed']


In [ ]:
np3 = np.array([True, False, False, True]) #False -> 0, True -> 1
print(np.sort(np3))

[False False  True  True]


In [ ]:
#2D
np4 = np.array([[6,7,1,9], [8,3,5,0]])
print(np4)
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]


#Searching

In [3]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
x = np.where(np1 == 3)#position is returned
print(np1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
(array([2]),)


In [5]:
print(x[0])

[2]


In [6]:
np1[x[0]]

array([3])

In [9]:
#return even items
y = np.where(np1 % 2 == 0)
y[0]

array([1, 3, 5, 7, 9])