In [1]:
import numpy as np

In [3]:
#1D array
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np1.shape

(12,)

In [ ]:
#2D array (rows, columns)
np2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
np2.shape

(2, 6)

In [8]:
#reshape
np3 = np1.reshape(3,4)
print(np1)
print(np3)
print(np3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [9]:
#reshape 3D
np4 = np1.reshape(2,3,2)
print(np4)
np4.shape

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


(2, 3, 2)

In [12]:
#Flatten to 1D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
