#Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
matrix = np.array([[1,2],[3,4]])
zeros = np.zeros((2,3))
ones = np.ones((2,2))
range_arr = np.arange(0,10,2)
linspace_arr = np.linspace(0,1,5)

In [5]:
print('Array', arr)
print('matrix', matrix)
print("zeros", zeros)
print('ones', ones)
print('array_range', range_arr)
print('linspace_arr', linspace_arr)

Array [1 2 3 4]
matrix [[1 2]
 [3 4]]
zeros [[0. 0. 0.]
 [0. 0. 0.]]
ones [[1. 1.]
 [1. 1.]]
array_range [0 2 4 6 8]
linspace_arr [0.   0.25 0.5  0.75 1.  ]


Attributes

In [6]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(4,)
1
4
int64


Indexing and slicing

In [7]:
print('first element',arr[0])
print('last element', arr[-1])
print('slice', arr[1:3])
print('row0, column1', matrix[0,1])
print('allrows, column1', matrix[:,1])

first element 1
last element 4
slice [2 3]
row0, column1 2
allrows, column1 [2 4]


Operations

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('sum of two arrays', a+b)
print('multiply two arrays', a*b)

sum of two arrays [5 7 9]
multiply two arrays [ 4 10 18]


Scalar

In [3]:
arr*2

array([2, 4, 6, 8])

Broadcasting

In [4]:
matrix + 10

array([[11, 12],
       [13, 14]])

Useful Functions

In [10]:
print('sum of an array', np.sum(arr))
print("mean of an array", np.mean(arr))
print("max value of an array", np.max(arr))
print("min value of an array", np.min(arr))

sum of an array 10
mean of an array 2.5
max value of an array 4
min value of an array 1


Reshaping and Flattening

In [11]:
arr = np.arange(1,7)
reshaped = arr.reshape(2,3)
flatten = reshaped.flatten()
print('array',arr)
print('reshape', reshaped)
print('flatten', flatten)

array [1 2 3 4 5 6]
reshape [[1 2 3]
 [4 5 6]]
flatten [1 2 3 4 5 6]


Stacking

In [13]:
a = np.array([1,2])
b = np.array([3,4])
print('vstack',np.vstack((a,b)))
print('hstack',np.hstack((a,b)))

vstack [[1 2]
 [3 4]]
hstack [1 2 3 4]


Boolean Indexing

In [14]:
arr = np.array([10,20,30,40])
print(arr[arr>20])

[30 40]


Random Arrays

In [15]:
uniform = np.random.rand(3,3)
normal_dist = np.random.randn(3,3)
integ = np.random.randint(1,10, size = (2,3))
print('uniform distri', uniform)
print('normal distri', normal_dist)
print('integer', integ)

uniform distri [[0.88270059 0.24486569 0.71697407]
 [0.83953955 0.11053194 0.40020515]
 [0.68984924 0.73238934 0.26829978]]
normal distri [[ 0.98619105 -1.07607993  1.60563356]
 [ 1.17483188  0.86464185  0.60169661]
 [-1.98655483  0.55753912 -1.31484177]]
integer [[1 4 6]
 [5 3 2]]


Linear Algebra

In [16]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print('dot matrix', np.dot(a,b))
print('Inverse', np.linalg.inv(a))
print('Determinant', np.linalg.det(a))

dot matrix [[19 22]
 [43 50]]
Inverse [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant -2.0000000000000004


Copy and View

In [17]:
arr = np.array([1,2,3])
view = arr.view()
copy = arr.copy()
print("view", view)
print('copy', copy)

view [1 2 3]
copy [1 2 3]
